beancount_filepath = "/Users/richardlyon/beancount"
start_date = "2024-01-01"

[[assets]]
name = "Personal"
account_type = "Assets"
currency = "GBP"
provider = "Starling"

[[liabilities]]
name = "AccountsPayable"
account_type = "Liabilities"
currency = "GBP"
provider = "Monzo"

[[equities]]
account_type = "Equities"
currency = "GBP"
provider = "Monzo"
name = "Opening-Balances"
