beancount_filepath = "/Users/richardlyon/beancount"
start_date = "2024-01-01"
provider = "Monzo"

[custom_categories]
category_0000AeU961sBDb6GUYcQh1 = "Subscriptions"
category_0000Aebc1dJeps1a2lDFKb = "InternetMobile"
category_0000AeNDWV8K5iX53Ohyld = "Car"
category_0000AiofUPXe8c5I6Zxp6g = "Clothing"
category_0000AebaqWt2Ie4L94Emkj = "Household"
category_0000Ae0SAST6Le7QACksGv = "Booze"
category_0000Aioey9weagAJdb8XMv = "Reading"
category_0000AiofRqvDslhZO2iK6z = "Medical"
category_0000AioenOrylFWbO3KVmL = "Hobby"
category_0000AeR7gxWtXy4Hzy0ULL = "Energy"
category_0000AgThBIKMlNhgpZPRhZ = "Maintenance"


# [[liabilities]]
# account_type = "Liabilities"
# currency = "GBP"
# account_name = "Personal"
# name = "AccountsPayable"

[[equities]]
account_type = "Equities"
currency = "GBP"
account_name = "Personal"
name = "Opening-Balances"
