beancount_filepath = "/Users/richardlyon/beancount"
start_date = "2024-01-01"

[custom_categories]
category_0000AeU961sBDb6GUYcQh1 = "UNKNOWN"
category_0000Aebc1dJeps1a2lDFKb = "UNKNOWN"
category_0000AeNDWV8K5iX53Ohyld = "UNKNOWN"
category_0000AiofUPXe8c5I6Zxp6g = "UNKNOWN"
category_0000AebaqWt2Ie4L94Emkj = "UNKNOWN"
category_0000Ae0SAST6Le7QACksGv = "UNKNOWN"
category_0000Aioey9weagAJdb8XMv = "UNKNOWN"
category_0000AiofRqvDslhZO2iK6z = "UNKNOWN"
category_0000AioenOrylFWbO3KVmL = "UNKNOWN"
category_0000AeR7gxWtXy4Hzy0ULL = "Energy"
category_0000AgThBIKMlNhgpZPRhZ = "UNKNOWN"

[[assets]]
name = "Personal"
account_type = "Assets"
currency = "GBP"
provider = "Starling"

[[liabilities]]
name = "AccountsPayable"
account_type = "Liabilities"
currency = "GBP"
provider = "Monzo"

[[equities]]
account_type = "Equities"
currency = "GBP"
provider = "Monzo"
name = "Opening-Balances"
